---
title: "Se aprende haciendo"
author: "Econ. Michael Solórzano"
date: "2024-03-01"
output: github_document
  
---
```{r}
library(dplyr)
data <- read.csv("C:\\Users\\bama1\\Desktop\\PROGRAMA CIENTIFICO DE DATOS\\Modulo 1\\BASES DE DATOS\\Iowa_Liquor_Sales_YG84CD.csv", stringsAsFactors = F, header = T)

datos <- data %>% 
  mutate(Sale..Dollars.=(as.numeric(substr(data$Sale..Dollars.,2,15))),
         City=toupper(City),
         Store.Name=toupper(Store.Name),
         Date=as.Date(Date,format="%m/%d/%Y"),
         anio=lubridate::year(Date)) %>% 
  rename(ventas=Sale..Dollars.,
         ciudad=City,
         Categoria=Category.Name,
         nombre_tienda=Store.Name)
```



```{r Top de 5 tiendas (promedio de ventas) para el año 2016,para la ciudad CEDAR RAPIDS}
datos %>% 
  group_by(ciudad,nombre_tienda,anio) %>% 
  summarise(Promedio_ventas=mean(ventas)) %>% 
  filter(ciudad=="CEDAR RAPIDS" & anio==2016) %>% 
  arrange(-Promedio_ventas) %>% 
  filter(Promedio_ventas>161)

#El top de las 5 tiendas que mas vendieron en la ciudad de CEDAR RAPIDS en el 2016 fueron: SAM'S CLUB 8162, FAREWAY STORES #151, BENZ DISTRIBUTING, LEO1 y TARGET STORE T-1771 


```

```{r ¿Cuáles fueron los 5 últimos vendedores (promedio de ventas, para el 2016, para DAVENPORT)? }
datos %>% 
  group_by(Vendor.Name,anio,ciudad) %>% 
  summarise(promedio_ventas=mean(ventas)) %>% 
  filter(anio==2016 & ciudad=="DAVENPORT") %>% 
  arrange(promedio_ventas) %>% 
  filter(promedio_ventas<43)

#Los vendedores que menos vendieron en la ciudad de DAVENPORT en el 2016 fueron: Luxco-St Louis, A HARDY USA LTD, Rumcoqui and Co, Prestige Wine & Spirits Group y Dehner Distillery

```

```{r ¿Cuál es el top 5 de productos más vendidos, para el 2016 y 2017, por ciudad?}
library(tidyverse)



datos %>%
  group_by(Item.Description,anio,ciudad) %>% 
  summarise(mas_vendidos=max(ventas)) %>% 
  filter(anio==2016) %>%
  arrange(-mas_vendidos) %>% 
  pivot_wider(names_from = ciudad,
              values_from = mas_vendidos,
              values_fill = 0)
#El top de ventas en el 2017 de los productos mas vendidos en las tres ciudades fueron: Cedar Ridge Barrel Aged Rum 5YR Reserve (este producto solo se vendio en CEDAR RAPIDS), Malibu Coconut Rum, Rumchata, Bailey's Original Irish Cream y Uv Blue (raspberry) Vodka


datos %>%
  group_by(Item.Description,anio,ciudad) %>% 
  summarise(mas_vendidos=max(ventas)) %>% 
  filter(anio==2017) %>%
  arrange(-mas_vendidos) %>% 
  pivot_wider(names_from = ciudad,
              values_from = mas_vendidos,
              values_fill = 0) 
#El top de ventas en el 2017 de los productos mas vendidos en las tres ciudades fueron: Godiva Liqueur, Godiva White Chocolate Liqueur, Bailey's Original Irish Cream, Bailey's Salted Caramel y Rumchata







  
```

